# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd0abe55f5708d1f2b615937b048e519ba5cef8bf92acc53e621126ef282b9e7ede1a79e7c152b77c214f8748ac9c7a4c1d598f12d815f8fa51eb4844259ec7d

test:
  secret_key_base: 048a1949d24b7f2568b15b532a1e7d1700a7855d04843062b160d6eedbda9d91f3593aa98666cf356a8375da1d0134dfa1ea7707477b523aff90cb4eade74700

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
